*** Variables ***
&{PRODUCTS}
...    labelHeader=//*[@id="inventory_filter_container"]/div
...    imageField=//*[@id="item_4_img_link"]
...    titleProduct=//*[@id="item_4_title_link"]/div
...    descriptionProduct=//*[@id="inventory_container"]/div/div[1]/div[2]/div
...    priceProduct=//*[@id="inventory_container"]/div/div[1]/div[3]/div
...    buttonProduct=//*[@id="inventory_container"]/div/div[1]/div[3]/button