name: Pipeline Test

on: push

jobs:
  test:
    name: Testes de API
    runs-on: ubuntu-latest

    steps:
      - name: Clonagem Projeto
        uses: actions/checkout@v3

      - name: Configuração do Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Instalar Dependencias do Projeto
        run: |
          pip install robotframework
          pip install robotframework-requests
          pip install robotframework-seleniumlibrary
      
      - name: Execução dos Testes Web
        run: |
          robot --outputdir results/ test-cases/

      - name: Salvando Resultado dos Testes
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: resultado-testes
          path: results
